---
#- name: Playbook for preparations
#  hosts: all
#
#  roles:
#  - role: osism.docker

- name: Playbook for role testing
  hosts: all

  vars:
    configuration_type: tarball
    configuration_tarball_name: kolla
    configuration_tarball_path: kolla
    configuration_tarball_protocol: http
    configuration_tarball_server: tarballs.openstack.org
    configuration_tarball_version: 4.0.0

  roles:
    - role: ansible-configuration

- name: Playbook for role testing
  hosts: all

  vars:
    configuration_type: git
    configuration_git_private_key: ""
    configuration_git_repository: https://github.com/osism/ansible-configuration.git
    configuration_git_version: master

  pre_tasks:
  - name: Remove existing configuration directory
    file:
      path: "{{ configuration_directory }}"
      state: absent
    become: true

  roles:
  - role: ansible-configuration
