# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Copy private ssh key of configuration repository
  copy:
    content: "{{ configuration_git_private_key }}"
    dest: "{{ configuration_git_private_key_file }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0600
  when:
    - configuration_git_private_key is defined
    - configuration_git_private_key != ''
  no_log: true

- name: Install git
  package:
    name: git
    state: present
  become: true

- name: Clone configuration repository using a keyfile
  git:
    repo: "{{ configuration_git_repository }}"
    dest: "{{ configuration_directory }}"
    version: "{{ configuration_git_version }}"
    key_file: "{{ configuration_git_private_key_file }}"
    accept_hostkey: yes
    force: yes
  when:
    - configuration_git_private_key is defined
    - configuration_git_private_key != ''

- name: Clone configuration repository without login
  git:
    repo: "{{ configuration_git_repository }}"
    dest: "{{ configuration_directory }}"
    version: "{{ configuration_git_version }}"
    accept_hostkey: yes
    force: yes
  when: configuration_git_private_key is not defined or configuration_git_private_key == ''
