# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Create configuration directory
  file:
    path: "{{ configuration_directory }}"
    owner: "{{ ansible_user }}"
    state: directory
    mode: 0750
  become: true

- name: Include tasks required by the specific configuration type
  include: "{{ configuration_type }}.yml"
