# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install python version 2 on ubuntu
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python version 2 on ubuntu
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    register: result
    changed_when: result.rc != 0
    become: true

- name: Playbook for role testing
  hosts: all

  vars:
    configuration_type: tarball

  pre_tasks:
  - name: Include vagrant variables
    include_vars: vars/vagrant.yml

  roles:
    - role: ../../ansible-configuration

- name: Playbook for role testing
  hosts: all

  vars:
    configuration_type: git

  pre_tasks:
  - name: Include vagrant variables
    include_vars: vars/vagrant.yml

  - name: Remove existing configuration directory
    file:
      path: "{{ configuration_directory }}"
      state: absent
    become: true

  roles:
  - role: ../../ansible-configuration
