---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: molecule-ubuntu-configuration
    image: ubuntu
    image_version: 16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - converge
    # - idempotence
    - lint
    - side_effect
    - verify
    - destroy
